<?php
		define("DB_HOST","localhost");
		define("DB_USER","root");
		define("DB_PASS","");
		define("DB_NAME","db_wellness");
		define('SITE_URL','http://'.$_SERVER["SERVER_NAME"].'/wellness/');
		define('COM_SITE_URL','http://'.$_SERVER["SERVER_NAME"].'/wellness/');
		define('NET_SITE_URL','http://'.$_SERVER["SERVER_NAME"].'/wellness/');
		define('BIZ_SITE_URL','http://'.$_SERVER["SERVER_NAME"].'/wellness/');
		define('SITE_ADMIN_URL',SITE_URL.'admin-nct/');
		define('DIR_URL',$_SERVER["DOCUMENT_ROOT"].'/wellness/');
		define('DIR_ADMIN_URL',DIR_URL.'admin-nct/');
